### ISSUE TITLE
[Finished in 2.4s with exit code 1]

### ISSUE THREAD

**Issue by richardbporter** [tsteur/sublimetext-tita#3]
Hi, great plugin.

When I run the Android emulator from ST2 using the super+alt+a shortcut I get the following error.

[Finished in 2.4s with exit code 1]

The app builds fine using the CLI, i.e. ti build -p android

**Comment by tsteur** [comment]
Hi,

maybe you need to set the Android SDK path in your Tita user settings? It's working pretty fine for me. The plugin executes the following command: "titanium build -p android -T device -A $androidSdkPath --log-level debug". Also make sure to execute "titanium setup" at least once.

Please note: I'll no longer maintain this plugin and I'll remove issues from this repository soon. I hope there is someone who wants to maintain it.
